# @baseUrl=http://localhost:3500/v1
##@baseUrl=https://memoriapo.herokuapp.com/v1
@host=http://localhost:3500

@auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTYzMzc2MjE1OSwiZXhwIjoxNjMzNzYyNzU5fQ.Vhy4OMeEC_Z5rDj52V6gx0w4pDJiQ9gk65iJYzHibfQ

### Get all decks
GET {{baseUrl}}/decks


### Get all cards from deck
GET {{baseUrl}}/deck/1/cards

#-----------  USERS CRUD -------------------------------

### login Toti
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email" : "toti@s.fr",
  "password" : "memoria!"
}

### login Tutu
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email" : "tutu@gmal.fr",
  "password" : "azerty"
}

### login Tuti
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email" : "tuti@gmal.fr",
  "password" : "azerty"
}

### login Nicoclock
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email" : "nico@clo.ck",
  "password" : "Nicocratie"
}

### login Tati
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email" : "tati@s.fr",
  "password" : "tata"
}

### login Nicoclock
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email" : "nico@clo.ck",
  "password" : "Nicocratie"
}


### login souleymane
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email" : "s.coulibaly@gmail.com",
  "password" : "souley92"
}

### Subscribe
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "name": "Nicoclock",
  "email" : "nico@clo.ck",
  "password" : "Nicocratie"
}


### Subscribe
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "name": "SOULEY",
  "email" : "s.coulibaly@gmail.com",
  "password" : "souley92"
}



### Update user info
POST {{baseUrl}}/user/update
Content-Type: application/json
Authorization: {{auth}}

{
  "name" : "TUTU du 69",
  "password" : "azerty"

}

### Get user infos
GET {{baseUrl}}/user/infos
# coller Authorization + token généré et founi par le serveur
Authorization: {{auth}}


#-----------  CARDS CRUD -------------------------------

### Get user cards
GET {{baseUrl}}/user/cards
# coller Authorization + token généré et founi par le serveur
Authorization: {{auth}}

### Add a card
POST {{baseUrl}}/card
Authorization: {{auth}}
Content-Type: application/json

{
    "deckId" : 7,
    "recto": "Une carte à faible durée de vie...",
    "verso": "...est amenée à disparaître mais pas tout de suite"
}

### Add a card
DELETE {{baseUrl}}/card
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJpYXQiOjE2MzQxMzU3OTksImV4cCI6MTYzNDEzNjk5OX0.4Hk6ffQMw9B3eCiwGCKIWGLTIZQ5hfIV0r-HbUykWJE
Content-Type: application/json

{
    "id" : 14
}


### Delay a card
POST {{baseUrl}}/card/delay
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJpYXQiOjE2MzQxMzU3OTksImV4cCI6MTYzNDEzNjk5OX0.4Hk6ffQMw9B3eCiwGCKIWGLTIZQ5hfIV0r-HbUykWJE
Content-Type: application/json

{
    "id" : 80
}

// GESTION DES DECKS


### Add a DECK
POST {{baseUrl}}/deck
Content-Type: application/json
Authorization: {{auth}}

{
    "title" : "Nouveau Deck Test",
    "tag": ["last chance", "test"]
}


# ### Tests benchmark Redis ...
# GET {{host}}/redis

# ### ... vs Postgres
# GET {{host}}/pg



