@baseUrl=http://localhost:3500/v1
# @baseUrl=https://memoriapo.herokuapp.com/v1
@host=http://localhost:3500

### Get all decks
GET {{baseUrl}}/decks


### Get all cards from deck
GET {{baseUrl}}/deck/1/cards

### Get user infos
GET {{baseUrl}}/user/infos
# coller Authorization + token généré et founi par le serveur
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTYzMjk0NjE3NywiZXhwIjoxNjMyOTQ2Mjk3fQ.P2PJUAo_zgjds4chRBvKsWrtBmuINMIKHZEnEHE3upk

### Get user cards
GET {{baseUrl}}/user/cards
# coller Authorization + token généré et founi par le serveur
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTYzMjk0NjE3NywiZXhwIjoxNjMyOTQ2Mjk3fQ.P2PJUAo_zgjds4chRBvKsWrtBmuINMIKHZEnEHE3upk

### login user
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email" : "toti@s.fr",
  "password" : "123456"
}

### Add a card

# POST {{baseUrl}}/card
# Content-Type: application/json 

# {
#     "recto": "Texte du recto",
#     "verso": "Texte du verso",
#     "deck_id": 1,
# }

# ### Tests benchmark Redis ...
# GET {{host}}/redis

# ### ... vs Postgres
# GET {{host}}/pg



