@baseUrl=http://localhost:3500/v1
@host=http://localhost:3500

### Get all decks
GET {{baseUrl}}/decks


### Get all cards from deck
GET {{baseUrl}}/deck/4/cards

### Get user infos
GET {{baseUrl}}/user/infos
# coller Authorization + token généré et founi par le serveur
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTYzMjUyNTIxNCwiZXhwIjoxNjMyNTI1MjQ0fQ.qvca96lHpiahlZNgSoxsiFNmMdm3L8yUggy8IIXco34
### login user
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email" : "tuti@gmal.fr",
  "password" : "azerty"
}

### Add a card

# POST {{baseUrl}}/card
# Content-Type: application/json 

# {
#     "recto": "Texte du recto",
#     "verso": "Texte du verso",
#     "deck_id": 1,
# }

# ### Tests benchmark Redis ...
# GET {{host}}/redis

# ### ... vs Postgres
# GET {{host}}/pg



select * from allcardsFromDeck(4);
SELECT AllcardsFromDeck(4);
select 



BEGIN;

INSERT INTO "user" ("name", "email", "password") VALUES 
('toti', 'toti@s.fr', '$2a$12$qI2JwszTvHE5MQ/bGJjLsu.7ggBc4Y/0fPSCapW9Kl4BiPKhaCQei'),
('tati', 'tati@s.fr', '$2a$12$941i1iAD0f1wi4uFCIJEW.6vRPaaewEqWrcP/db.MGyd99IQj3yAC'),
('tuti', 'tuti@gmal.fr', '$2a$12$TR6HsCh.675u7woRZelZFOntwmv6ZDy1lVAQJDgt9hIqHAiu48zqK');

INSERT INTO deck (title, user_id, tag) VALUES 
('Un gros paquet', 1, '{"Javascript", "Saison 0"}'),
('Un très gros paquet', 3, '{"Express", "Saison 5"}'),
('Un beau paquet', 2, '{"React", "Saison 2"}'),
('Un tout petit paquet', 2, '{"PHP", "Saison 2"}')
;

INSERT INTO "card" ("recto", "verso", deck_id) VALUES 
('Pourquoi ?', 'Parce que...', 1),
('Mais pourquoi ?', 'Mais parce que...', 4),
('Pourquoi ?', 'Ta gueule !', 2);

INSERT INTO delay ("user_id", "card_id") VALUES
(1,1), 
(2,3), 
(1,1);

COMMIT;


BEGIN;
INSERT INTO deck (title, user_id) VALUES 
('Toti Paquet 1', 1),
('Toti Paquet 2', 1),
('Toti Paquet 3', 1),
('Toti Paquet 4', 1),
('Tati Paquet 1', 2),
('Tati Paquet 2', 2),
('Tati Paquet 3', 2),
('Tati Paquet 4', 2),
('Tuti Paquet 1', 3),
('Tuti Paquet 2', 3),
('Tuti Paquet 3', 3),
('Tuti Paquet 4', 3);
COMMIT;